### ISSUE TITLE
Is it a good practice to use Repository Pattern in Laravel?

### ISSUE THREAD

**Issue by amitleuva1987** [ManiruzzamanAkash/Laravel-Advanced-CRUD-API#2]
@ManiruzzamanAkash , I see you have used "Repository pattern" in this git repo. Is it a good practice to use repository pattern in Laravel. 

I mean the controller code could have been more shorter if you would have not used repositories. The objective of the SOLID principles is to shorten the controller but in your case, it looks like the controller code has widen with repositories.

Please don't take it as an issue. I am just learning these design patterns and SOLID principles and just want to discuss it with experienced developers.

**Comment by ManiruzzamanAkash** [comment]
We can work in controller only.
But consider, some of the scenarios for getting product lists.

1. We need to get the product list based on some conditions, searching or other parameters.
2. We need to make then repetitive code if we don't make a reusable way for this. otherwise it would break the DRY concept.
3. Also testing is an important part, creating new instance of Controller is not recommended, rather create new instance for Repository.


We could also make every method in a separate controller with a singleton pattern or static method. But, that is also not good for Testing.

So, I think Repository pattern is well enough. Definitely, we could make this more segregated by implementing some other design patterns, but intentionally I've made this simpler.
